# Generated by Django 3.1.14 on 2022-06-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Women',
            new_name='Celebs',
        ),
    ]
